version: '3.7'
services:

  zoo1:
    image: cithub/zookeeper
    hostname: zoo1
    container_name: zoo1
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - ./data/zoo1/datalog:/datalog
      - ./data/zoo1/data:/data
      - ./data/zoo1/logs:/logs
    networks:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    command: --serviceExecutor adaptive
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - mongo

networks:
  mongo: